"""Initial migration with all models

Revision ID: 6d646413299d
Revises: 
Create Date: 2025-12-08 14:54:12.043454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d646413299d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Hacer la migración idempotente: verificar si las tablas existen antes de crearlas
    from sqlalchemy import inspect, text
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Si hay tablas de aplicación existentes, probablemente ya se aplicaron migraciones anteriores
    # En producción, la tabla alembic_version tendrá una revisión antigua que ya no existe en el código
    # En este caso, Alembic intentará ejecutar esta migración, pero como las tablas ya existen,
    # simplemente las saltaremos (idempotente) y Alembic actualizará alembic_version automáticamente
    # No necesitamos hacer nada especial aquí, la lógica idempotente de abajo se encarga
    
    # ### commands auto generated by Alembic - please adjust! ###
    if 'city_boundary' not in existing_tables:
        op.create_table('city_boundary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('polygon', sa.Text(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'district' not in existing_tables:
        op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
        )
    
    if 'role' not in existing_tables:
        op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    
    if 'user' not in existing_tables:
        op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=255), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier'),
        sa.UniqueConstraint('username')
        )
    
    if 'donation' not in existing_tables:
        op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('donation_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('stripe_session_id')
        )
    
    if 'initiative' not in existing_tables:
        op.create_table('initiative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('image_path', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        
        # Crear índice solo si la tabla fue creada (no existía antes)
        # Si la tabla ya existía, el índice debería existir también
        if 'initiative' not in existing_tables:
            with op.batch_alter_table('initiative', schema=None) as batch_op:
                batch_op.create_index(batch_op.f('ix_initiative_slug'), ['slug'], unique=True)
        else:
            # Si la tabla ya existía, verificar si el índice existe
            try:
                indexes = inspector.get_indexes('initiative')
                index_names = [idx['name'] for idx in indexes]
                if 'ix_initiative_slug' not in index_names:
                    with op.batch_alter_table('initiative', schema=None) as batch_op:
                        batch_op.create_index(batch_op.f('ix_initiative_slug'), ['slug'], unique=True)
            except Exception:
                # Si falla la verificación, intentar crear el índice de todas formas
                try:
                    with op.batch_alter_table('initiative', schema=None) as batch_op:
                        batch_op.create_index(batch_op.f('ix_initiative_slug'), ['slug'], unique=True)
                except Exception:
                    # Si el índice ya existe, ignorar el error
                    pass
    
    if 'report_purchase' not in existing_tables:
        op.create_table('report_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('report_params', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('download_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('download_token'),
        sa.UniqueConstraint('stripe_session_id')
        )
    
    if 'roles_users' not in existing_tables:
        op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
        )
    
    if 'section' not in existing_tables:
        op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('district_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('polygon', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_code'], ['district.code'], ),
    sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('district_code', 'code', name='unique_district_section')
        )
    
    if 'comment' not in existing_tables:
        op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('initiative_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiative.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'inventory_item' not in existing_tables:
        op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('image_path', sa.String(length=300), nullable=True),
    sa.Column('image_gps_latitude', sa.Float(), nullable=True),
    sa.Column('image_gps_longitude', sa.Float(), nullable=True),
    sa.Column('location_source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('importance_count', sa.Integer(), nullable=True),
    sa.Column('resolved_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'section_responsible' not in existing_tables:
        op.create_table('section_responsible',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'section_id', name='unique_user_section')
        )
    
    if 'user_initiatives' not in existing_tables:
        op.create_table('user_initiatives',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('initiative_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiative.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
        )
    
    if 'inventory_resolved' not in existing_tables:
        op.create_table('inventory_resolved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('item_id', 'user_id', name='unique_item_user_resolved')
        )
    
    if 'inventory_vote' not in existing_tables:
        op.create_table('inventory_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'user_id', name='unique_item_user_vote')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_vote')
    op.drop_table('inventory_resolved')
    op.drop_table('user_initiatives')
    op.drop_table('section_responsible')
    op.drop_table('inventory_item')
    op.drop_table('comment')
    op.drop_table('section')
    op.drop_table('roles_users')
    op.drop_table('report_purchase')
    with op.batch_alter_table('initiative', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_initiative_slug'))

    op.drop_table('initiative')
    op.drop_table('donation')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('district')
    op.drop_table('city_boundary')
    # ### end Alembic commands ###
