"""add container overflow reports

Revision ID: 293421593054
Revises: 911345c1b0f4
Create Date: 2025-12-18 14:52:34.306705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293421593054'
down_revision = '911345c1b0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_overflow_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_point_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['container_point_id'], ['container_point.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_point_id', 'user_id', name='unique_container_user_overflow_report')
    )
    with op.batch_alter_table('container_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overflow_reports_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_point', schema=None) as batch_op:
        batch_op.drop_column('overflow_reports_count')

    op.drop_table('container_overflow_report')
    # ### end Alembic commands ###
