"""add container points model

Revision ID: 911345c1b0f4
Revises: a9b798e3d195
Create Date: 2025-12-17 23:37:56.786891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911345c1b0f4'
down_revision = 'a9b798e3d195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('polygon', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_overflow_report', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('container_point', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_container_point_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_container_point_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_point', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_container_point_status'))
        batch_op.drop_index(batch_op.f('ix_container_point_section_id'))

    op.drop_table('container_point')
    # ### end Alembic commands ###
