"""container suggestion

Revision ID: bcf387f506da
Revises: 293421593054
Create Date: 2025-12-20 15:45:09.536399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf387f506da'
down_revision = '293421593054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_point_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('suggested_by_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['suggested_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('container_point_suggestion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_container_point_suggestion_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_container_point_suggestion_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_point_suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_container_point_suggestion_status'))
        batch_op.drop_index(batch_op.f('ix_container_point_suggestion_section_id'))

    op.drop_table('container_point_suggestion')
    # ### end Alembic commands ###
