"""Add slug field to initiatives

Revision ID: 6a9481a976b8
Revises: 
Create Date: 2025-11-06 13:06:12.730220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '6a9481a976b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Check if initiative table exists, if not create it
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'initiative' not in existing_tables:
        # Create initiative table (for new databases like staging)
        op.create_table('initiative',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=200), nullable=False),
            sa.Column('slug', sa.String(length=250), nullable=True),  # Will be set to NOT NULL below
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('location', sa.String(length=200), nullable=False),
            sa.Column('category', sa.String(length=50), nullable=False),
            sa.Column('date', sa.Date(), nullable=False),
            sa.Column('time', sa.String(length=10), nullable=True),
            sa.Column('image_path', sa.String(length=300), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('view_count', sa.Integer(), nullable=True),
            sa.Column('creator_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('slug')
        )
        # Index is automatically created by UniqueConstraint, no need to create it manually
    
    # Now modify the slug column (works for both existing and newly created tables)
    with op.batch_alter_table('initiative', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('initiative', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
