"""City boundaries

Revision ID: 842ac89522f9
Revises: 8bc3cd31c05f
Create Date: 2025-12-02 16:37:07.348230

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '842ac89522f9'
down_revision = '8bc3cd31c05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_boundary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('polygon', sa.Text(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city_boundary')
    # ### end Alembic commands ###
