"""Remove category and subcategory fields from InventoryItem, use many-to-many relationship

Revision ID: 46a3cbac6d0c
Revises: ce62a193da56
Create Date: 2026-01-09 22:29:46.000341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a3cbac6d0c'
down_revision = 'ce62a193da56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('subcategory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Nota: El downgrade requiere valores por defecto ya que los campos eran NOT NULL
    # En producción, esto requeriría migrar datos desde inventory_item_categories
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory', sa.VARCHAR(length=50), autoincrement=False, nullable=True, server_default=''))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True, server_default=''))
        # Hacer los campos NOT NULL después de añadirlos (requiere datos)
        # batch_op.alter_column('category', nullable=False)
        # batch_op.alter_column('subcategory', nullable=False)

    # ### end Alembic commands ###
