"""Add InventoryCategory model and inventory_item_categories association table

Revision ID: 16ba43ca206c
Revises: bc198fdcdbb3
Create Date: 2026-01-03 15:52:17.947045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ba43ca206c'
down_revision = 'bc198fdcdbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['inventory_category.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_category_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_category_parent_id'), ['parent_id'], unique=False)

    op.create_table('inventory_item_categories',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_category.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_item_categories')
    with op.batch_alter_table('inventory_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_category_parent_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_category_code'))

    op.drop_table('inventory_category')
    # ### end Alembic commands ###
