"""Add donations table

Revision ID: 4444556b09c4
Revises: b1caaf81c024
Create Date: 2025-11-10 17:18:41.106581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '4444556b09c4'
down_revision = 'b1caaf81c024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create donation table (check if it exists first)
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'donation' not in existing_tables:
        op.create_table('donation',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('amount', sa.Integer(), nullable=False),
            sa.Column('currency', sa.String(length=3), nullable=True),
            sa.Column('email', sa.String(length=255), nullable=True),
            sa.Column('stripe_session_id', sa.String(length=255), nullable=False),
            sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=True),
            sa.Column('donation_type', sa.String(length=50), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('completed_at', sa.DateTime(), nullable=True),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('stripe_session_id')
        )
    
    # Drop temporary table if it exists (leftover from failed migration)
    try:
        op.drop_table('_alembic_tmp_inventory_item')
    except:
        pass  # Table might not exist
    
    # Note: subcategory NOT NULL constraint is already applied in the database
    # No need to modify inventory_item table

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.alter_column('subcategory',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.create_table('_alembic_tmp_inventory_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('reporter_id', sa.INTEGER(), nullable=True),
    sa.Column('importance_count', sa.INTEGER(), nullable=True),
    sa.Column('subcategory', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('donation')
    # ### end Alembic commands ###
