"""Add District and Section models with PostGIS support

Revision ID: 5645985c853c
Revises: 8c313c3157bd
Create Date: 2025-12-01 13:26:28.043955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5645985c853c'
down_revision = '8c313c3157bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('district_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('polygon', sa.Text(), nullable=False),  # WKT format, can be converted to PostGIS Geometry for PostgreSQL
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_code'], ['district.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_code', 'code', name='unique_district_section')
    )
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inventory_item_section_id', 'section', ['section_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_item_section_id', type_='foreignkey')
        batch_op.drop_column('section_id')

    op.drop_table('section')
    op.drop_table('district')
    # ### end Alembic commands ###
