"""Add subcategory field to InventoryItem

Revision ID: 8eac5677c563
Revises: 4908fda2abca
Create Date: 2025-11-10 11:34:22.111418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eac5677c563'
down_revision = '4908fda2abca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration adds subcategory field to inventory_item table
    # Compatible with both PostgreSQL (production) and SQLite (development)
    
    connection = op.get_bind()
    is_postgresql = connection.dialect.name == 'postgresql'
    is_sqlite = connection.dialect.name == 'sqlite'
    
    # Check if column already exists (in case of partial migration)
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('inventory_item')]
    
    # Only add column if it doesn't exist
    if 'subcategory' not in columns:
        # Add column as nullable first (required for data migration)
        op.add_column('inventory_item', sa.Column('subcategory', sa.String(length=50), nullable=True))
    
    # Migrate existing data: map old category values to new category->subcategory structure
    # Old categories that were subcategories under 'palomas':
    connection.execute(sa.text("""
        UPDATE inventory_item 
        SET subcategory = category,
            category = 'palomas'
        WHERE category IN ('excremento', 'nido', 'paloma', 'plumas')
    """))
    
    # Old categories that are now under 'basura':
    connection.execute(sa.text("""
        UPDATE inventory_item 
        SET subcategory = category,
            category = 'basura'
        WHERE category IN ('basura_desborda', 'vertidos')
    """))
    
    # Handle 'otro' category (if any exists, map to palomas->otro)
    connection.execute(sa.text("""
        UPDATE inventory_item 
        SET subcategory = COALESCE(subcategory, 'otro'),
            category = 'palomas'
        WHERE subcategory IS NULL
    """))
    
    # Make column NOT NULL (PostgreSQL supports ALTER COLUMN, SQLite doesn't)
    if is_postgresql:
        try:
            op.alter_column('inventory_item', 'subcategory', nullable=False, existing_type=sa.String(length=50))
        except Exception as e:
            # Log but don't fail - column might already be NOT NULL
            print(f"⚠️  Could not set NOT NULL constraint: {e}")
    # For SQLite, we can't easily change NOT NULL constraint after creation
    # The application will ensure subcategory is always set for new items

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore old category values before dropping subcategory
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE inventory_item 
        SET category = subcategory
        WHERE category = 'palomas' OR category = 'basura'
    """))
    
    op.drop_column('inventory_item', 'subcategory')

    # ### end Alembic commands ###
