"""Add subcategory field to InventoryItem

Revision ID: 8eac5677c563
Revises: 4908fda2abca
Create Date: 2025-11-10 11:34:22.111418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eac5677c563'
down_revision = '4908fda2abca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists (in case of partial migration)
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('inventory_item')]
    
    # Only add column if it doesn't exist
    if 'subcategory' not in columns:
        # Add column as nullable first
        op.add_column('inventory_item', sa.Column('subcategory', sa.String(length=50), nullable=True))
    
    # Migrate existing data: map old category values to new category->subcategory structure
    # Old categories that were subcategories under 'palomas':
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE inventory_item 
        SET subcategory = category,
            category = 'palomas'
        WHERE category IN ('excremento', 'nido', 'paloma', 'plumas')
    """))
    
    # Old categories that are now under 'basura':
    connection.execute(sa.text("""
        UPDATE inventory_item 
        SET subcategory = category,
            category = 'basura'
        WHERE category IN ('basura_desborda', 'vertidos')
    """))
    
    # Handle 'otro' category (if any exists, map to palomas->otro)
    connection.execute(sa.text("""
        UPDATE inventory_item 
        SET subcategory = 'otro',
            category = 'palomas'
        WHERE category = 'otro' OR subcategory IS NULL
    """))
    
    # Make column NOT NULL (works for PostgreSQL, SQLite will skip this)
    # Check if we're using PostgreSQL
    if connection.dialect.name == 'postgresql':
        try:
            op.alter_column('inventory_item', 'subcategory', nullable=False)
        except Exception:
            # If it fails, continue (might be SQLite)
            pass
    elif connection.dialect.name == 'sqlite':
        # For SQLite, we can't easily change NOT NULL constraint
        # The application will ensure subcategory is always set for new items
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore old category values before dropping subcategory
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE inventory_item 
        SET category = subcategory
        WHERE category = 'palomas' OR category = 'basura'
    """))
    
    op.drop_column('inventory_item', 'subcategory')

    # ### end Alembic commands ###
