"""Change initiative status default to pending

Revision ID: b1caaf81c024
Revises: 8eac5677c563
Create Date: 2025-11-10 16:56:59.949648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1caaf81c024'
down_revision = '8eac5677c563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support changing column defaults directly
    # The default is handled at the application level in the model
    # This migration is a no-op for SQLite, but ensures the schema is consistent
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support changing column defaults directly
    pass
    # ### end Alembic commands ###
